version: '3.7'
networks: 
  az_docker_network: 
    driver: bridge
services:
  php:
    build:
      context: ./php
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    container_name: az_docker_php
    working_dir: "/var/www/clients"
    restart: always
    networks: 
      - az_docker_network
    volumes: 
      - "../:/var/www/clients"
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    container_name: az_docker_nginx
    restart: always
    working_dir: "/var/www/clients"
    networks: 
      - az_docker_network
    volumes: 
      - "../:/var/www/clients"
      - "./nginx/:/etc/nginx/conf.d/"
  mariadb:
    build:
      context: ./mariadb
      dockerfile: Dockerfile
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Az#86*123
    ports:
      - "3306:3306"
    container_name: az_docker_mariadb
    volumes: 
      - "./mariadb/data-mariadb:/var/lib/mysql"
    networks: 
      - az_docker_network
  redis:
    build:
      context: ./redis
      dockerfile: Dockerfile
    volumes: 
      - "./redis/cache:/data"
    container_name: az_docker_redis
    restart: always
    networks: 
      - az_docker_network
    ports:
      - "6379:6379"      
volumes:
  ms-sqlserver-data:
    driver: local
